appname = casdoor
httpport = 8000
runmode = dev
copyrequestbody = true
driverName = mysql
dataSourceName = root:niro-mysql-2026@tcp(127.0.0.1:3306)/
dbName = casdoor
showSql = false
redisEndpoint =
defaultStorageProvider =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
defaultApplication = "app-built-in"
enableGzip = true
logConfig = {"adapter":"console"}
initDataNewOnly = true
initDataFile = __INIT_PATH__
