#!/usr/bin/env bash
# Ensure the deterministic baseline is up and generate ../credentials.yaml and
# ../fixtures.yaml from it.
#
# Seeding itself happens inside the app: main.go calls object.InitFromFile()
# on every boot, which reads init_data.seed.json (via the initDataFile env var
# start.sh sets) and reconciles the "acme" org/app/users to match it exactly
# (delete + recreate when they already differ). initDataNewOnly=false makes
# this authoritative, not additive. The always-present built-in org/admin
# come from Casdoor's own object.InitDb() bootstrap on first-ever boot
# (admin/123 in org "built-in").
#
# So seed.sh's own job is: (1) make sure the server is running (start.sh is a
# no-op if it's already healthy), (2) read back the one value that is
# generated randomly at seed time (the OAuth clientId/clientSecret for
# app-acme) from the sqlite DB, and (3) render credentials.yaml/fixtures.yaml.
set -euo pipefail
HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$HARNESS_DIR/lib.sh"

"$HARNESS_DIR/start.sh"

if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "[seed] FATAL: sqlite3 CLI not found, cannot read back app-acme's generated OAuth client credentials" >&2
  exit 1
fi

# Give the very first post-boot InitFromFile() pass a moment to finish writing
# if start.sh's health check raced it (health comes up before InitFromFile
# completes in rare cold-start cases); retry the read a few times.
read_app_acme_client() {
  sqlite3 -separator '|' "$DB_FILE" \
    "select client_id, client_secret from application where owner='admin' and name='app-acme' limit 1;" 2>/dev/null
}

CLIENT_ROW=""
for _ in $(seq 1 10); do
  CLIENT_ROW="$(read_app_acme_client || true)"
  if [ -n "$CLIENT_ROW" ]; then
    break
  fi
  sleep 1
done

if [ -z "$CLIENT_ROW" ]; then
  echo "[seed] FATAL: app-acme row not found in $DB_FILE after seeding" >&2
  exit 1
fi

APP_ACME_CLIENT_ID="${CLIENT_ROW%%|*}"
APP_ACME_CLIENT_SECRET="${CLIENT_ROW##*|}"

read_user_id() {
  # $1=owner $2=name
  sqlite3 "$DB_FILE" "select id from user where owner='$1' and name='$2' limit 1;" 2>/dev/null
}

ADMIN_ID="$(read_user_id built-in admin || true)"
ALICE_ID="$(read_user_id acme alice || true)"
BOB_ID="$(read_user_id acme bob || true)"
ACME_ADMIN_ID="$(read_user_id acme acme-admin || true)"

cat > "$CREDENTIALS_FILE" <<EOF
# yaml-language-server: \$schema=https://niro.apxlabs.ai/schema/v1/credentials.json
# GENERATED by niro/harness/seed.sh — do not hand-edit, re-run seed.sh instead.
credentials:
  - credential_id: GLOBAL_ADMIN
    description: "Built-in Casdoor global admin, created automatically by
      Casdoor's own first-boot bootstrap (object.InitDb()), owner org
      \"built-in\". Effective privilege: user.IsGlobalAdmin() in
      object/user.go returns true for ANY user whose Owner == \"built-in\",
      regardless of the IsAdmin flag — this account also has IsAdmin=true so
      it is unambiguously the top-level admin. Global admin can manage every
      organization, user, application, cert, provider, role, permission,
      group, and record in the instance. Login: POST $BASE_URL/api/login,
      JSON {\"username\":\"admin\",\"password\":\"...\",\"organization\":
      \"built-in\",\"application\":\"app-built-in\",\"type\":\"login\"}
      (type required). Use to verify standard users and the Acme org-admin
      are denied instance-wide admin surfaces (org management, other orgs'
      users, /api/get-organizations, provider/cert management)."
    type: username_password
    identifier: admin
    secret: "$ADMIN_PASSWORD"

  - credential_id: ACME_STANDARD_A
    description: "Standard non-admin user \"alice\" in org \"acme\" (a
      dedicated test tenant seeded by niro/harness/init_data.seed.json, owner
      != \"built-in\" so IsGlobalAdmin() is false and IsAdmin=false — no
      elevated capability of any kind). Owns her own Casdoor user profile
      (acme/alice) only. Login: POST $BASE_URL/api/login with JSON body
      {\"username\":\"alice\",\"password\":\"...\",\"organization\":\"acme\",
      \"application\":\"app-acme\",\"type\":\"login\"} (type required).
      Pair with ACME_STANDARD_B for
      horizontal-escalation tests: authenticate as alice, attempt to
      read/modify bob's profile (acme/bob) via /api/get-user,
      /api/update-user, /api/get-user-application etc., expect 403/owner
      mismatch. Pair with GLOBAL_ADMIN and ACME_ORG_ADMIN for
      vertical-escalation tests against org-management and cross-org
      endpoints."
    type: username_password
    identifier: alice
    secret: "$ALICE_PASSWORD"

  - credential_id: ACME_STANDARD_B
    description: "Standard non-admin user \"bob\" in org \"acme\", same shape
      as ACME_STANDARD_A (alice) but a DIFFERENT principal owning a
      different user profile (acme/bob) so cross-user access attempts from
      alice have something real to fail at. Login: same shape as
      ACME_STANDARD_A with username=\"bob\"."
    type: username_password
    identifier: bob
    secret: "$BOB_PASSWORD"

  - credential_id: ACME_ORG_ADMIN
    description: "Org-scoped admin \"acme-admin\", Owner=\"acme\" (NOT
      \"built-in\"), IsAdmin=true. Per object/user.go IsApplicationAdmin(): an
      admin whose Owner equals the application's Organization can administer
      that application/org (acme, app-acme) — e.g. manage acme's own users,
      roles, permissions. Per IsGlobalAdmin() (Owner==\"built-in\" only) this
      account is NOT a global admin: it should be denied instance-wide
      surfaces (managing org \"built-in\", other organizations, global
      provider/cert config, /api/get-organizations across tenants). Login:
      POST $BASE_URL/api/login with JSON body {\"username\":\"acme-admin\",
      \"password\":\"...\",\"organization\":\"acme\",\"application\":
      \"app-acme\",\"type\":\"login\"} (type required). Pair with GLOBAL_ADMIN to verify org-admin privileges
      stop at the acme org boundary (org-isolation / tenant-boundary
      testing) — this is the primary account for that class of test."
    type: username_password
    identifier: acme-admin
    secret: "$ACME_ADMIN_PASSWORD"

  - credential_id: ACME_APP_OAUTH_CLIENT
    description: "OAuth2 client_id/client_secret pair for application
      app-acme (org acme), auto-generated by Casdoor on seed
      (object.AddApplication) and read back from the sqlite DB by seed.sh —
      rotates on every reset/reseed. Use for client_credentials /
      authorization_code / token endpoint testing at $BASE_URL/api/login/
      oauth/access_token and $BASE_URL/api/login/oauth/authorize. Distinct
      code path from human username_password logins above — use to probe
      whether the service/client-credential path silently inherits
      human-admin privileges or bypasses org scoping. identifier is the
      OAuth client_id; secret is the OAuth client_secret."
    type: username_password
    identifier: "$APP_ACME_CLIENT_ID"
    secret: "$APP_ACME_CLIENT_SECRET"
EOF

cat > "$FIXTURES_FILE" <<EOF
# yaml-language-server: \$schema=https://niro.apxlabs.ai/schema/v1/fixtures.json
# GENERATED by niro/harness/seed.sh — do not hand-edit, re-run seed.sh instead.
fixtures:
  - name: base_url
    description: "Base URL of the Niro-managed Casdoor instance under test."
    value: "$BASE_URL"

  - name: built_in_organization
    description: "Casdoor's always-present built-in organization. Owner field
      value that org-membership checks compare against (see
      object/user.go IsGlobalAdmin: Owner==\"built-in\"). Home of the
      GLOBAL_ADMIN credential and the default app-built-in application."
    value:
      name: built-in
      display_name: "Built-in Organization"
      default_application: app-built-in

  - name: acme_organization
    description: "Dedicated test tenant seeded by
      niro/harness/init_data.seed.json, reconciled (delete+recreate) on
      every server start/reset. Home of ACME_STANDARD_A/B and
      ACME_ORG_ADMIN. Use for tenant-isolation tests: built-in-org
      principals should not read/write acme data and vice versa."
    value:
      name: acme
      display_name: "Acme Corp (Niro test tenant)"
      default_application: app-acme

  - name: app_built_in
    description: "Default Casdoor application/OAuth client for the built-in
      organization, auto-created by object.InitDb() on first-ever boot.
      Owner: admin. organization: built-in."
    value:
      owner: admin
      name: app-built-in
      organization: built-in

  - name: app_acme
    description: "OAuth application/client for org acme, seeded from
      init_data.seed.json. Its live client_id/client_secret are the
      ACME_APP_OAUTH_CLIENT credential (they rotate on reseed, so they live
      in credentials.yaml, not here)."
    value:
      owner: admin
      name: app-acme
      organization: acme
      redirect_uri: "http://localhost:${HTTP_PORT}/callback"

  - name: acme_users
    description: "The three acme-org principals seeded alongside the org,
      with their internal Casdoor user IDs (primary key 'id' column,
      distinct from the owner/name pair used in most API paths). Useful for
      API calls that key off id rather than owner+name."
    value:
      alice:
        owner: acme
        name: alice
        id: "${ALICE_ID:-unknown}"
        is_admin: false
      bob:
        owner: acme
        name: bob
        id: "${BOB_ID:-unknown}"
        is_admin: false
      acme-admin:
        owner: acme
        name: acme-admin
        id: "${ACME_ADMIN_ID:-unknown}"
        is_admin: true

  - name: global_admin_user
    description: "Internal Casdoor user ID for built-in/admin (the
      GLOBAL_ADMIN credential's principal)."
    value:
      owner: built-in
      name: admin
      id: "${ADMIN_ID:-unknown}"

  - name: health_check_endpoint
    description: "Unauthenticated liveness endpoint used by start.sh to know
      the server is up; returns 200 with no auth required."
    value: "$BASE_URL/api/health"

  - name: login_endpoint
    description: "Username/password login endpoint used by all
      username_password credentials above. POST JSON body:
      {username, password, organization, application, type:\"login\"} — type
      is REQUIRED, omitting it returns HTTP 200 status:\"error\" instead of
      authenticating (controllers/auth.go dispatches on form.Type). On
      success sets the casdoor_session_id cookie."
    value: "$BASE_URL/api/login"
EOF

echo "[seed] wrote $CREDENTIALS_FILE"
echo "[seed] wrote $FIXTURES_FILE"
