#!/usr/bin/env bash
# Verify the Sieve baseline and generate ../credentials.yaml and
# ../fixtures.yaml.
#
# Sieve has no external DB: USERS is a hardcoded, in-memory dict seeded at
# process start (alice/bob/admin). There is nothing to provision over the
# network — "seeding" here means (1) make sure the app is up, (2) prove the
# baked-in accounts actually authenticate, and (3) emit the credential/fixture
# catalog Niro reads on every run.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

if ! container_running; then
  echo "sieve: app not running — starting it first..." >&2
  "$SCRIPT_DIR/start.sh"
fi

wait_for_health 30

login() {
  # $1 username  $2 password -> prints token on stdout, fails on non-200
  local username="$1" password="$2"
  local resp
  resp="$(curl -fsS -X POST "${BASE_URL}/login" \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"${username}\",\"password\":\"${password}\"}")"
  python3 -c 'import json,sys; print(json.load(sys.stdin)["token"])' <<<"$resp"
}

echo "sieve: verifying seeded users can authenticate..." >&2
ALICE_TOKEN="$(login alice alice-pw)"
BOB_TOKEN="$(login bob bob-pw)"
ADMIN_TOKEN="$(login admin admin-pw)"

for pair in "alice:$ALICE_TOKEN" "bob:$BOB_TOKEN" "admin:$ADMIN_TOKEN"; do
  name="${pair%%:*}"
  tok="${pair#*:}"
  if [ -z "$tok" ]; then
    echo "sieve: login verification failed for ${name}" >&2
    exit 1
  fi
  echo "sieve: ${name} login OK (token ${tok})" >&2
done

# GET /admin/users is reachable with no auth at all in current app.py — sanity
# check it responds so fixtures below (account ids) are trustworthy.
curl -fsS "${BASE_URL}/admin/users" >/dev/null \
  || { echo "sieve: GET /admin/users did not respond as expected" >&2; exit 1; }

CREDS_FILE="$NIRO_DIR/credentials.yaml"
FIXTURES_FILE="$NIRO_DIR/fixtures.yaml"

cat >"$CREDS_FILE" <<'EOF'
# Generated by niro/harness/seed.sh — do not edit by hand, regenerate instead.
# See niro/credentials.yaml.example for the format reference.
credentials:
  - credential_id: STANDARD_USER_ALICE
    description: "Standard (non-admin) user, id=1, owns account /accounts/1
      (balance 100). admin=false in the USERS record. Login: POST /login
      with JSON body {\"username\":\"alice\",\"password\":...} -> {\"token\"}.
      Use the token as `Authorization: Bearer <token>` on GET
      /accounts/<id>. Pair with STANDARD_USER_BOB for horizontal-escalation
      tests (Alice reading Bob's account or vice versa) since each owns a
      different account id with a different balance."
    type: username_password
    identifier: alice
    secret: "alice-pw"

  - credential_id: STANDARD_USER_BOB
    description: "Standard (non-admin) user, id=2, owns account /accounts/2
      (balance 8400). admin=false in the USERS record. Same login shape as
      Alice: POST /login {\"username\":\"bob\",\"password\":...} -> {\"token\"}.
      Different resource (account id, balance) from Alice so cross-user
      access attempts have something to fail at."
    type: username_password
    identifier: bob
    secret: "bob-pw"

  - credential_id: GLOBAL_ADMIN
    description: "Admin user, id=3, admin=true in the USERS record (the only
      seeded account with this flag). Login: POST /login
      {\"username\":\"admin\",\"password\":...} -> {\"token\"}. Use to test
      whether GET /admin/users (full user directory, including passwords) is
      properly gated to admins only — standard users Alice/Bob should not be
      able to reach the same data/effect via that route or any other."
    type: username_password
    identifier: admin
    secret: "admin-pw"
EOF

cat >"$FIXTURES_FILE" <<EOF
# Generated by niro/harness/seed.sh — do not edit by hand, regenerate instead.
# See niro/fixtures.yaml.example for the format reference.
fixtures:
  - name: seeded_accounts
    description: "Account ids for the three in-memory seeded users, for use
      against GET /accounts/<id>. Each user should only need their own id
      for legitimate use; use the others to probe horizontal access."
    value:
      alice: {id: 1, username: alice, email: alice@sieve.test, balance: 100, admin: false}
      bob: {id: 2, username: bob, email: bob@sieve.test, balance: 8400, admin: false}
      admin: {id: 3, username: admin, email: admin@sieve.test, balance: 0, admin: true}

  - name: login_endpoint
    description: "Shape of the login call every seeded credential above uses."
    value:
      method: POST
      path: /login
      body: {username: "<identifier>", password: "<secret>"}
      response: {token: "token-<user id>"}

  - name: account_endpoint
    description: "Authenticated account-detail lookup. Requires an
      Authorization: Bearer <token> header from any successful /login (the
      route does not check that the token's owner matches <id>)."
    value:
      method: GET
      path: "/accounts/<id>"
      auth_header: "Authorization: Bearer <token>"

  - name: admin_users_endpoint
    description: "Full user directory dump, including plaintext passwords.
      No Authorization header is required by the current implementation."
    value:
      method: GET
      path: /admin/users
      auth_header: none
EOF

echo "sieve: wrote $CREDS_FILE" >&2
echo "sieve: wrote $FIXTURES_FILE" >&2
echo "sieve: seed complete — baseline verified at ${BASE_URL}" >&2
