#!/usr/bin/env bash
# Sieve has no real seeding step: USERS is a fixed, in-memory dict baked into
# app.py (alice, bob, admin) and is always present the instant the container
# starts. This script's job is therefore just to emit the deterministic
# niro/credentials.yaml and niro/fixtures.yaml that describe that baseline,
# and to confirm the target is actually up first.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIRO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RUN_DIR="$SCRIPT_DIR/run"

HOST_PORT="${SIEVE_HOST_PORT:-5000}"
BASE_URL="http://localhost:${HOST_PORT}"
if [ -f "$RUN_DIR/base_url" ]; then
  BASE_URL="$(cat "$RUN_DIR/base_url")"
fi

echo "[seed] checking $BASE_URL/ is reachable..."
if ! curl -fsS "$BASE_URL/" >/dev/null 2>&1; then
  echo "[seed] FAILED: $BASE_URL/ is not reachable. Run start.sh first." >&2
  exit 1
fi

echo "[seed] writing $NIRO_DIR/credentials.yaml..."
cat > "$NIRO_DIR/credentials.yaml" <<EOF
# yaml-language-server: \$schema=https://niro.apxlabs.ai/schema/v1/credentials.json
#
# GENERATED by niro/harness/seed.sh — do not edit by hand, re-run seed.sh instead.
#
# Sieve seeds exactly these 3 users as a fixed in-memory dict in app.py; there
# is no signup flow and no database, so these are the only identities that
# will ever exist for this target.

credentials:
  - credential_id: STANDARD_USER_ALICE
    description: "Standard (non-admin) user 'alice', user id 1, balance 100,
      email alice@sieve.test. Login: POST /login with JSON body
      {\"username\":\"alice\",\"password\":\"alice-pw\"} -> {\"token\":\"token-1\"}.
      Send the token as 'Authorization: Bearer <token>' on GET /accounts/<id>.
      Pair with STANDARD_USER_BOB for horizontal-escalation tests: authenticate
      as alice (account id 1) and attempt to read bob's account (id 2) via
      GET /accounts/2, expect 401/403/404 rather than bob's balance/email.
      Also pair with GLOBAL_ADMIN for vertical-escalation tests against
      GET /admin/users, which alice must not be able to reach as an admin
      would (note: in the current implementation /admin/users requires no
      token at all, so this is expected to fail open for every credential)."
    type: username_password
    identifier: alice
    secret: "alice-pw"

  - credential_id: STANDARD_USER_BOB
    description: "Standard (non-admin) user 'bob', user id 2, balance 8400,
      email bob@sieve.test. Login: POST /login with JSON body
      {\"username\":\"bob\",\"password\":\"bob-pw\"} -> {\"token\":\"token-2\"}.
      Send the token as 'Authorization: Bearer <token>' on GET /accounts/<id>.
      Owns a different account/balance than alice, so cross-user access
      attempts (bob reading GET /accounts/1, alice reading GET /accounts/2)
      have something concrete to fail at. Pair with STANDARD_USER_ALICE for
      horizontal-escalation tests."
    type: username_password
    identifier: bob
    secret: "bob-pw"

  - credential_id: GLOBAL_ADMIN
    description: "Admin user 'admin', user id 3, balance 0, email
      admin@sieve.test, admin flag true in the user record (the only user
      with admin=true). Login: POST /login with JSON body
      {\"username\":\"admin\",\"password\":\"admin-pw\"} -> {\"token\":\"token-3\"}.
      Send the token as 'Authorization: Bearer <token>' on GET /accounts/<id>.
      Pair with STANDARD_USER_ALICE and STANDARD_USER_BOB for
      vertical-escalation tests: the standard users must not be able to do
      anything admin-only that admin can. Note: GET /admin/users in the
      current implementation requires no authentication/token at all and
      returns the full user directory including plaintext passwords for
      every credential above, admin or not -- this is a known intentional
      vulnerability of this deliberately-weak app, not a mis-scoped
      credential."
    type: username_password
    identifier: admin
    secret: "admin-pw"
EOF

echo "[seed] writing $NIRO_DIR/fixtures.yaml..."
cat > "$NIRO_DIR/fixtures.yaml" <<EOF
# yaml-language-server: \$schema=https://niro.apxlabs.ai/schema/v1/fixtures.json
#
# GENERATED by niro/harness/seed.sh — do not edit by hand, re-run seed.sh instead.

fixtures:
  - name: base_url
    description: "Base URL Sieve is listening on for this boot. All endpoints
      in the endpoint list below are relative to this."
    value: "${BASE_URL}"

  - name: endpoints
    description: "Full endpoint list for Sieve (see GET / and README.md).
      GET / returns this list plus a warning that the app is intentionally
      vulnerable. POST /login authenticates and returns a bearer token.
      GET /accounts/<id> returns account details for a numeric id and
      requires an 'Authorization: Bearer <token>' header (any valid token
      from any user is currently accepted for any account id -- token
      identity is not checked against the requested id). GET /admin/users
      returns the entire in-memory user directory, including plaintext
      passwords, with no authentication required at all."
    value:
      index: "GET /"
      login: "POST /login"
      account_by_id: "GET /accounts/<id>"
      admin_users: "GET /admin/users"

  - name: user_alice
    description: "Fixture data for seeded user alice, paired with
      STANDARD_USER_ALICE credential. Account id 1 is what
      GET /accounts/1 should return when authorized correctly."
    value:
      id: 1
      username: alice
      email: alice@sieve.test
      balance: 100
      admin: false

  - name: user_bob
    description: "Fixture data for seeded user bob, paired with
      STANDARD_USER_BOB credential. Account id 2 is what GET /accounts/2
      should return when authorized correctly. Use to verify alice cannot
      read this account (horizontal escalation) via GET /accounts/2."
    value:
      id: 2
      username: bob
      email: bob@sieve.test
      balance: 8400
      admin: false

  - name: user_admin
    description: "Fixture data for seeded user admin, paired with
      GLOBAL_ADMIN credential. Account id 3 is what GET /accounts/3 should
      return when authorized correctly. This is the only user with
      admin=true in the user record."
    value:
      id: 3
      username: admin
      email: admin@sieve.test
      balance: 0
      admin: true
EOF

echo "[seed] done: credentials.yaml and fixtures.yaml written to $NIRO_DIR"
