#!/usr/bin/env sh
set -eu

HARNESS_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
NIRO_DIR=$(CDPATH= cd -- "$HARNESS_DIR/.." && pwd)
PROJECT_ROOT=$(CDPATH= cd -- "$NIRO_DIR/.." && pwd)
RUN_DIR="$HARNESS_DIR/run"
PROJECT_NAME="${NIRO_COMPOSE_PROJECT_NAME:-chatwoot_niro}"

export HARNESS_DIR
export NIRO_DIR
export PROJECT_ROOT
export CHATWOOT_RAILS_PORT="${CHATWOOT_RAILS_PORT:-3300}"
export CHATWOOT_VITE_PORT="${CHATWOOT_VITE_PORT:-3336}"
export CHATWOOT_POSTGRES_PORT="${CHATWOOT_POSTGRES_PORT:-6432}"
export CHATWOOT_REDIS_PORT="${CHATWOOT_REDIS_PORT:-16379}"
export CHATWOOT_SMTP_PORT="${CHATWOOT_SMTP_PORT:-11025}"
export CHATWOOT_MAILHOG_PORT="${CHATWOOT_MAILHOG_PORT:-18025}"
export REDIS_PASSWORD="${REDIS_PASSWORD:-chatwoot_niro}"

compose() {
  docker compose -p "$PROJECT_NAME" -f "$HARNESS_DIR/compose.yaml" "$@"
}

write_env() {
  mkdir -p "$RUN_DIR"
  cat > "$RUN_DIR/app.env" <<EOF
SECRET_KEY_BASE=niro_local_secret_key_base_0123456789abcdef0123456789abcdef0123456789abcdef
ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=0123456789abcdef0123456789abcdef
ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=abcdef0123456789abcdef0123456789
ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=0123456789abcdef0123456789abcdef
FRONTEND_URL=http://localhost:${CHATWOOT_RAILS_PORT}
FORCE_SSL=false
ENABLE_ACCOUNT_SIGNUP=true
ENABLE_ACCOUNT_SEEDING=true
ENABLE_RACK_ATTACK=false
ENABLE_RACK_ATTACK_WIDGET_API=false
MAX_USER_SESSIONS=200
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DATABASE=chatwoot_niro
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=chatwoot_niro
POSTGRES_STATEMENT_TIMEOUT=60s
RAILS_ENV=development
RAILS_MAX_THREADS=5
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:chatwoot_niro@redis:6379/0
MAILER_SENDER_EMAIL=Chatwoot Niro <accounts@niro.local>
SMTP_ADDRESS=mailhog
SMTP_PORT=1025
SMTP_AUTHENTICATION=
SMTP_ENABLE_STARTTLS_AUTO=false
ACTIVE_STORAGE_SERVICE=local
RAILS_LOG_TO_STDOUT=true
LOG_LEVEL=info
CW_API_ONLY_SERVER=false
ENABLE_PUSH_RELAY_SERVER=false
SAFE_FETCH_ALLOW_PRIVATE_NETWORK=false
VITE_RUBY_HOST=0.0.0.0
EOF
}

wait_for_http() {
  url="$1"
  label="$2"
  attempts="${3:-90}"
  i=1
  while [ "$i" -le "$attempts" ]; do
    if curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
    i=$((i + 1))
  done
  echo "$label did not become healthy at $url" >&2
  return 1
}
