#!/usr/bin/env bash
# Generate ../credentials.yaml and ../fixtures.yaml describing the
# deterministic baseline OWASP Juice Shop always creates on startup.
#
# Juice Shop needs no separate seeding step: server.ts runs
# `sequelize.sync({ force: true })` followed by `datacreator()` on every
# boot (see server.ts ~line 734 and data/datacreator.ts), which drops and
# recreates all tables and repopulates them from the static fixtures in
# data/static/*.yml and config/default.yml (`products`). That happens
# inside start.sh already. This script's job is narrower: make sure the
# app is up, prove the intended test actors can actually authenticate
# against THIS boot, and emit the two manifest files Niro reads.
#
# Idempotent: safe to re-run; overwrites the two generated files.

set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${HARNESS_DIR}/../.." && pwd)"
NIRO_DIR="${ROOT_DIR}/niro"
PORT="${PORT:-3000}"
BASE_URL="http://localhost:${PORT}"

# Make sure the app is up (no-op if already healthy).
"${HARNESS_DIR}/start.sh"

login_ok() {
  local email="$1" password="$2"
  local body
  body=$(curl -s -X POST "${BASE_URL}/rest/user/login" \
    -H 'Content-Type: application/json' \
    -d "$(python3 - "$email" "$password" <<'PY'
import json, sys
print(json.dumps({"email": sys.argv[1], "password": sys.argv[2]}))
PY
)")
  if ! echo "${body}" | grep -q '"token"'; then
    echo "[seed] FAILED to authenticate ${email} against ${BASE_URL}: ${body}" >&2
    return 1
  fi
}

echo "[seed] verifying seeded test actors can authenticate..." >&2
login_ok "jim@juice-sh.op" "ncc-1701"
login_ok "bender@juice-sh.op" "OhG0dPlease1nsertLiquor!"
login_ok "admin@juice-sh.op" "admin123"
login_ok "accountant@juice-sh.op" "i am an awesome accountant"
login_ok "ciso@juice-sh.op" "mDLx?94T~1CfVfZMzw@sJ9f?s3L6lbMqE70FfI8^54jbNikY5fymx7c!YbJb"
echo "[seed] all actors authenticated OK" >&2

# --- credentials.yaml -------------------------------------------------
# Passwords below are the plaintext values from data/static/users.yml,
# the app's own committed seed data (loaded by data/datacreator.ts on
# every boot). Emails are `${key}@${application.domain}`
# (config/default.yml: application.domain = juice-sh.op), per the
# email-construction rule in data/datacreator.ts::createUsers.
cat > "${NIRO_DIR}/credentials.yaml" <<'EOF'
# GENERATED by niro/harness/seed.sh — do not hand-edit, re-run the script.
credentials:
  - description: "Standard user A (role customer, id 1 basket 2). Owns
      Basket #2 (Raspberry Juice), a saved address, a payment card, and
      an authored product-store feedback comment. Login: POST
      /rest/user/login with JSON body {email, password}; response is
      {authentication:{token, bid, umail}} — send the token as
      `Authorization: Bearer <token>` on subsequent requests. Pair with
      Standard user B (bender) for horizontal-escalation tests: authenticate
      as jim, attempt to read/modify bender's basket (/rest/basket/3),
      orders, or address/card records, expect denial."
    type: username_password
    identifier: jim@juice-sh.op
    secret: "ncc-1701"

  - description: "Standard user B (role customer, id 3, basket 3). Owns
      Basket #3 (Raspberry Juice), a saved address, a payment card, and
      one submitted complaint (/api/Complaints, message about building a
      competing e-commerce business). Login: same shape as jim. Different
      resources from jim so cross-user access attempts have something to
      fail at. Pair with jim for horizontal-escalation tests."
    type: username_password
    identifier: bender@juice-sh.op
    secret: "OhG0dPlease1nsertLiquor!"

  - description: "Global admin (role admin, id 1, basket 1). Login: POST
      /rest/user/login, same body shape as the standard users. Note: this
      app's backend authorization is only PARTIALLY role-gated — most
      /api/* CRUD routes (e.g. POST /api/Products, GET+POST
      /api/Complaints, GET /api/Users) are reachable by ANY authenticated
      user via security.isAuthorized() regardless of role (see
      server.ts); only a few surfaces enforce role explicitly:
      /rest/order-history/orders requires role=accounting (see
      lib/insecurity.ts isAccounting), and the Angular admin routes/guards
      gate the /#/administration UI client-side. Use this admin to test
      whether standard users (jim, bender) and the accounting/deluxe
      principals below can reach admin-labeled surfaces that should be
      admin-only."
    type: username_password
    identifier: admin@juice-sh.op
    secret: "admin123"

  - description: "Accounting principal (role accounting, id 15). The ONLY
      role explicitly checked server-side via lib/insecurity.ts
      isAccounting(): gates GET /rest/order-history/orders (view every
      user's orders) and the Angular accounting UI. Login: same shape as
      the standard users. Use to verify standard users and the deluxe
      principal are rejected at /rest/order-history/orders, and that this
      principal itself cannot reach admin-only surfaces requiring role
      admin specifically (if any exist beyond isAuthorized())."
    type: username_password
    identifier: accountant@juice-sh.op
    secret: "i am an awesome accountant"

  - description: "Deluxe-membership customer (role deluxe, id 5, basket
      7). Holds a deluxeToken (see lib/insecurity.ts deluxeToken /
      isDeluxe) granting deluxe pricing and access to deluxe-exclusive
      products; otherwise a normal customer with its own basket, distinct
      from jim/bender. Login: same shape as the standard users. Use to
      test deluxe-gated surfaces (e.g. deluxe pricing/checkout) and as a
      third identity for horizontal-escalation checks against jim/bender
      resources."
    type: username_password
    identifier: ciso@juice-sh.op
    secret: "mDLx?94T~1CfVfZMzw@sJ9f?s3L6lbMqE70FfI8^54jbNikY5fymx7c!YbJb"
EOF

echo "[seed] wrote ${NIRO_DIR}/credentials.yaml" >&2

# --- fixtures.yaml ------------------------------------------------------
# Product ids/names read live from the running app (they come from
# config/default.yml `products`, in insertion order) so fixtures.yaml
# always matches what's actually seeded, even if the product list changes.
PRODUCTS_JSON=$(curl -s "${BASE_URL}/rest/products/search?q=juice")
APPLE_ID=$(echo "${PRODUCTS_JSON}" | python3 -c "import json,sys; d=json.load(sys.stdin); print(next(p['id'] for p in d['data'] if p['name'].startswith('Apple Juice')))")
RASPBERRY_ID=$(echo "${PRODUCTS_JSON}" | python3 -c "import json,sys; d=json.load(sys.stdin); print(next(p['id'] for p in d['data'] if p['name'].startswith('Raspberry Juice')))")

cat > "${NIRO_DIR}/fixtures.yaml" <<EOF
# GENERATED by niro/harness/seed.sh — do not hand-edit, re-run the script.
fixtures:
  - name: base_url
    description: "Base URL of the Niro-managed Juice Shop instance."
    value: "${BASE_URL}"

  - name: login_endpoint
    description: "Login call for every credential in credentials.yaml.
      POST JSON {email, password}; success returns
      {authentication:{token, bid, umail}}. Send the token back as
      \`Authorization: Bearer <token>\`. Failure (wrong creds) returns
      401 {status:'totp_token_required'} only for the 2FA test account
      (wurstbrot, not in credentials.yaml) or generic 401 otherwise."
    value:
      method: POST
      path: /rest/user/login
      body_shape: { email: string, password: string }

  - name: admin_basket
    description: "Admin's (id 1) own basket — expect 200 when admin
      requests it, 403/404 when jim or bender request it."
    value:
      basket_id: 1
      user_id: 1
      contains_product_ids: [${APPLE_ID}]

  - name: jim_basket
    description: "jim's (id 2) own basket, seeded with Raspberry Juice.
      Use for horizontal-escalation checks from bender/ciso/accountant."
    value:
      basket_id: 2
      user_id: 2
      contains_product_ids: [${RASPBERRY_ID}]

  - name: bender_basket
    description: "bender's (id 3) own basket, seeded with Raspberry
      Juice. Use for horizontal-escalation checks from jim/ciso/accountant."
    value:
      basket_id: 3
      user_id: 3
      contains_product_ids: [${RASPBERRY_ID}]

  - name: bender_complaint
    description: "Complaint pre-seeded for bender (UserId 3) via
      data/datacreator.ts::createComplaints, reachable at GET
      /api/Complaints (isAuthorized() only — any authenticated user, not
      just bender, can currently list it; a candidate authorization
      finding). Message: \"I'll build my own eCommerce business! With
      Black Jack! And Hookers!\""
    value:
      user_id: 3

  - name: representative_product_ids
    description: "A few of the ~35 seeded products
      (config/default.yml \`products\`, created fresh by
      data/datacreator.ts::createProducts on every boot) for exercising
      /rest/products/search, /rest/products/:id/reviews, and
      /rest/basket/:id (add-to-basket) flows."
    value:
      apple_juice: ${APPLE_ID}
      raspberry_juice: ${RASPBERRY_ID}

  - name: search_endpoint
    description: "Unauthenticated product search. Known-vulnerable to
      SQL injection via the \`q\` parameter (intentional Juice Shop
      challenge) — useful as a ground-truth positive when calibrating
      injection test cases."
    value:
      method: GET
      path: /rest/products/search
      query_param: q

  - name: file_upload_endpoints
    description: "Authenticated file-upload surfaces to exercise:
      POST /file-upload (multipart field 'file'; accepts .zip/.xml/.yml
      complaint attachments, each with dedicated parsing — zip-slip,
      XXE, and YAML-deserialization are intentional challenge surfaces
      here), POST /profile/image/file (multipart field 'file', profile
      picture), POST /profile/image/url (JSON/form field 'file' as a
      URL — SSRF-shaped), POST /rest/memories (multipart field 'image',
      requires auth via security.appendUserId())."
    value:
      routes:
        - { method: POST, path: /file-upload, field: file }
        - { method: POST, path: /profile/image/file, field: file }
        - { method: POST, path: /profile/image/url, field: file }
        - { method: POST, path: /rest/memories, field: image }

  - name: complaint_endpoint
    description: "Authenticated complaint submission. POST /api/Complaints
      with JSON {message, file?} (base64 PDF attachment supported per
      the pre-seeded anonymous-feedback comment referencing 'only order
      confirmation PDFs can be attached to complaints'). GET
      /api/Complaints lists ALL complaints for ANY authenticated user
      (isAuthorized() only, no ownership filter) — see bender_complaint
      fixture above."
    value:
      method: POST
      path: /api/Complaints

  - name: order_history_accounting
    description: "Accounting-only endpoint returning every user's orders
      across the whole app. Requires role=accounting
      (lib/insecurity.ts isAccounting()); expect 403 for jim, bender,
      ciso, and even admin (admin's role is 'admin', not 'accounting')."
    value:
      method: GET
      path: /rest/order-history/orders
EOF

echo "[seed] wrote ${NIRO_DIR}/fixtures.yaml" >&2
echo "[seed] done" >&2
