#!/usr/bin/env bash
#
# Niro harness: seed
#
# crAPI self-seeds its baseline on every boot:
#   - crapi-identity (InitialDataConfig, ApplicationReadyEvent) creates 5
#     predefined users, one vehicle each, and a profile video, iff the user
#     table is empty. Source:
#     services/identity/src/main/java/com/crapi/config/InitialDataConfig.java
#     services/identity/src/main/java/com/crapi/constant/TestUsers.java
#   - crapi-workshop (runner.sh -> manage.py seed_database) creates 2
#     mechanics, 2 shop products, up to 5 service reports and up to 5 orders,
#     get-or-create, on every container start. Source:
#     services/workshop/core/management/commands/seed_database.py
#   - crapi-community (LoadMongoData, called from server.go on boot) creates
#     3 coupons and 10 forum posts (authored by the 3 predefined
#     ROLE_PREDEFINE users) iff those Mongo collections are empty. Source:
#     services/community/api/seed/seeder.go
#
# This script does NOT re-implement that seeding. It:
#   1. Waits for the app to be reachable.
#   2. Re-invokes the app's own idempotent seed entry points so the baseline
#      is reconciled even if this is called against an already-running,
#      partially-mutated stack (get-or-create semantics -> safe to re-run).
#   3. Emits niro/credentials.yaml and niro/fixtures.yaml describing that
#      baseline, per niro/credentials.yaml.example and
#      niro/fixtures.yaml.example.
#
# This is the single generator for both files; reset.sh calls this script
# after restoring a clean baseline so the two always describe the same state.

set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIRO_DIR="$(cd "$HARNESS_DIR/.." && pwd)"
REPO_ROOT="$(cd "$NIRO_DIR/.." && pwd)"
DOCKER_DIR="$REPO_ROOT/deploy/docker"

BASE_URL="${CRAPI_BASE_URL:-http://localhost:8888}"
MAILHOG_URL="${CRAPI_MAILHOG_URL:-http://localhost:8025}"

echo "[seed] Waiting for $BASE_URL/health ..."
ok=0
for i in $(seq 1 60); do
  if curl -fsS "$BASE_URL/health" >/dev/null 2>&1; then
    ok=1
    break
  fi
  sleep 2
done
if [ "$ok" != "1" ]; then
  echo "[seed] ERROR: $BASE_URL is not reachable. Run start.sh first." >&2
  exit 1
fi

echo "[seed] Reconciling workshop fixtures (products, mechanics, reports, orders)..."
if ! (cd "$DOCKER_DIR" && docker compose -f docker-compose.yml exec -T crapi-workshop python3 manage.py seed_database); then
  echo "[seed] WARN: workshop seed_database reconcile failed or was already fully seeded; continuing." >&2
fi

echo "[seed] Reconciling predefined identity test-user passwords to their seed defaults..."
if ! curl -fsS -X POST "$BASE_URL/identity/api/auth/reset-test-users" -H 'Content-Type: application/json' >/dev/null; then
  echo "[seed] WARN: reset-test-users call failed; predefined users may already be at defaults." >&2
fi

echo "[seed] Writing $NIRO_DIR/credentials.yaml ..."
cat > "$NIRO_DIR/credentials.yaml" <<'EOF'
# GENERATED by niro/harness/seed.sh — do not edit by hand, edit the generator.
credentials:
  # --- ROLE_PREDEFINE users: horizontal-escalation trio ---
  # These three (Adam, Pogba, Robot) are functionally standard users. Each
  # owns exactly one vehicle (fixed VIN/carId baked into
  # services/identity/src/main/java/com/crapi/constant/TestUsers.java, so
  # they are stable across reseeds) and authored a subset of the 10 seeded
  # community forum posts (round-robin over these three emails; see
  # services/community/api/seed/seeder.go). No admin/mechanic flags.
  # Login: POST /identity/api/auth/login body {"email":..., "password":...}
  # (via the gateway at http://localhost:8888/identity/api/auth/login).
  # Pair any two of Adam/Pogba/Robot/Test for horizontal-escalation tests:
  # authenticate as one, attempt to read/modify another's vehicle
  # (/identity/api/v2/vehicle/*), profile, or forum posts/comments; expect
  # 403/404, not the other user's data.
  - description: "Standard user 'Adam' (ROLE_PREDEFINE, functionally a
      regular user, no elevated flags). Owns vehicle carId
      f89b5f21-7829-45cb-a650-299a61090378, VIN 7ECOX34KJTV359804. Authored
      several of the 10 seeded community forum posts. Login: POST
      /identity/api/auth/login body {email, password}."
    type: username_password
    identifier: adam007@example.com
    secret: "adam007!123"

  - description: "Standard user 'Pogba' (ROLE_PREDEFINE, functionally a
      regular user, no elevated flags). Owns vehicle carId
      cd515c12-0fc1-48ae-8b61-9230b70a845b, VIN 8VAUI03PRUQ686911. Authored
      several of the 10 seeded community forum posts. Different vehicle and
      posts from Adam and Robot, so cross-user access attempts have
      something to fail at. Login: same shape as Adam."
    type: username_password
    identifier: pogba006@example.com
    secret: "pogba006!123"

  - description: "Standard user 'Robot' (ROLE_PREDEFINE, functionally a
      regular user, no elevated flags). Owns vehicle carId
      4bae9968-ec7f-4de3-a3a0-ba1b2ab5e5e5, VIN 0NKPZ09IHOP508673. Authored
      several of the 10 seeded community forum posts. Different vehicle and
      posts from Adam and Pogba. Login: same shape as Adam."
    type: username_password
    identifier: robot001@example.com
    secret: "robot001!123"

  # --- Plain ROLE_USER: vertical-escalation partner for Admin ---
  - description: "Standard user 'Test' (ROLE_USER, no elevated flags). Owns
      vehicle carId 1929186d-8b67-4163-a208-de52a41f7301, VIN
      8IGEF39BZUJ159285. Has none of Adam/Pogba/Robot's forum posts. Use to
      verify admin-only endpoints (/identity/management/admin/lockUser,
      workshop /workshop/api/management/users/all, community
      /community/api/v2/coupon/new-coupon) reject a plain user, and
      mechanic-only endpoints (/workshop/api/mechanic/*) reject a plain
      user. Login: POST /identity/api/auth/login body {email, password}."
    type: username_password
    identifier: test@example.com
    secret: "Test!123"

  # --- Admin: vertical-escalation target, ALSO the chatbot's backing identity ---
  - description: "Global admin 'Admin' (ROLE_ADMIN). Owns vehicle carId
      f5c506f5-3af2-4120-926c-64ad8b10ddc2, VIN 6NBBY70FWUM324316. Login:
      POST /identity/api/auth/login body {email, password}. Vertical-
      escalation target: Test/Adam/Pogba/Robot (ROLE_USER/ROLE_PREDEFINE)
      and Jhon/James (ROLE_MECHANIC) must NOT reach admin-only surfaces
      (/identity/management/admin/lockUser to lock another user's account,
      workshop /workshop/api/management/users/all) — authenticate as the
      lower-privileged user and verify these reject. ALSO holds a
      cross-cutting capability outside the role system: this exact account
      (admin@example.com / Admin!123) is the crapi-chatbot service's own
      backing identity for its server-side OpenAPI/RAG actions against
      identity-service (see API_USER/API_PASSWORD in
      deploy/docker/docker-compose.yml, crapi-chatbot service). Admin acting
      through the chatbot's tool-calling path is by design, not an
      impersonation finding."
    type: username_password
    identifier: admin@example.com
    secret: "Admin!123"

  # --- Mechanics: separate ROLE_MECHANIC surface, horizontal pair ---
  - description: "Mechanic 'Jhon' (ROLE_MECHANIC, mechanic_code TRAC_JHN),
      seeded by services/workshop/core/management/commands/seed_database.py.
      Can reach /workshop/api/mechanic/* (service_requests, mechanic_report,
      download_report, service comments). Service requests are assigned
      randomly across the 2 seeded mechanics at boot, so Jhon and James may
      each be assigned different service_request IDs — use to test whether
      one mechanic can read/act on a service request or report assigned to
      the other mechanic (BOLA). Login: POST /identity/api/auth/login body
      {email, password} (mechanics authenticate through identity-service
      like any other user; role is ROLE_MECHANIC)."
    type: username_password
    identifier: jhon@example.com
    secret: "Admin1@#"

  - description: "Mechanic 'James' (ROLE_MECHANIC, mechanic_code TRAC_JME),
      seeded the same way as Jhon. Pair with Jhon for horizontal-escalation
      tests on /workshop/api/mechanic/* (service requests / reports /
      comments), and with Test/Adam/Pogba/Robot for vertical-escalation
      tests confirming plain users cannot reach mechanic-only endpoints.
      Login: same shape as Jhon."
    type: username_password
    identifier: james@example.com
    secret: "Admin1@#"
EOF

echo "[seed] Writing $NIRO_DIR/fixtures.yaml ..."
cat > "$NIRO_DIR/fixtures.yaml" <<EOF
# GENERATED by niro/harness/seed.sh — do not edit by hand, edit the generator.
fixtures:
  - name: base_url
    description: "Public gateway (crapi-web/nginx) all services are proxied
      through. Use as the root for every request; do not call service
      containers directly. Also serves the SPA at /."
    value: ${BASE_URL}

  - name: service_paths
    description: "Path prefixes crapi-web proxies to each backend, all under
      base_url. /identity -> crapi-identity (Java/Spring, auth+users+vehicles),
      /community -> crapi-community (Go, forum posts+coupons),
      /workshop -> crapi-workshop (Python/Django, shop+mechanic+orders+admin
      user list), /chatbot -> crapi-chatbot (Python, LLM chatbot + genai
      init), /mailhog -> mailhog web UI/API (all app email, domain
      example.com, is captured here, nothing leaves the host),
      /.well-known/jwks.json -> identity JWKS."
    value:
      identity: /identity
      community: /community
      workshop: /workshop
      chatbot: /chatbot
      mailhog: /mailhog
      jwks: /.well-known/jwks.json

  - name: mailhog_direct_url
    description: "MailHog web UI + JSON API (GET /api/v2/messages) reachable
      directly on its own published port, equivalent to base_url/mailhog/.
      All crAPI outbound mail (signup verification, forget-password OTP,
      email-change confirmation) is captured here since every address uses
      the example.com domain, which the identity/workshop SMTP config routes
      to this MailHog instance."
    value: ${MAILHOG_URL}

  - name: chatbot_mcp_port
    description: "crapi-chatbot's MCP server, published directly (not
      proxied by crapi-web) per deploy/docker/docker-compose.yml. Separate
      attack surface from the /chatbot HTTP API above."
    value: "localhost:5500"

  - name: enabled_vulnerable_flags
    description: "This harness starts crapi-identity with these two
      normally-off feature flags enabled (config-only, via
      niro/harness/start.sh; deploy/docker/.env itself still defaults both
      to false) so both surfaces are in scope: (1) shell command injection —
      set a profile video's conversion_params via PUT
      /identity/api/v2/user/videos/{video_id}, then trigger conversion via
      GET /identity/api/v2/user/videos/convert_video (see
      ProfileController/ProfileServiceImpl); it builds and executes
      'convertVideo -i VIDEO_NAME CONVERSION_PARAMS' via Runtime.exec
      with conversion_params unsanitized — inject shell metacharacters
      there. (2) Log4Shell — crapi-identity bundles
      log4j-core 2.14.0 (CVE-2021-44228, affects <=2.14.1); POST
      /identity/api/auth/login with an email value containing the literal
      substring 'jndi:' reaches a vulnerable log4j format call in
      UserServiceImpl.authenticateUserLogin. Both require a network egress
      target (callback host/LDAP listener) you control to observe
      exploitation; crapi-identity's own egress is unrestricted by this
      harness."
    value:
      ENABLE_SHELL_INJECTION: true
      ENABLE_LOG4J: true

  - name: ssrf_gateway_host
    description: "api.mypremiumdealership.com — a second, internal-only
      backend (services/gateway-service) that crapi-identity is configured
      to call out to (API_GATEWAY_URL env var) from
      /identity/api/v2/vehicle/register_vehicle and
      /identity/api/v2/vehicle/resend_email. It is NOT published on a host
      port and is not directly reachable from outside the compose network
      by design — it exists so those two identity endpoints can be probed
      for SSRF (attacker-controlled URL forcing identity-service to reach
      arbitrary internal hosts instead of this one)."
    value: api.mypremiumdealership.com

  - name: predefined_vehicles
    description: "Fixed carId/VIN pairs for the 4 non-mechanic seeded users,
      from services/identity/src/main/java/com/crapi/constant/TestUsers.java.
      Stable across reseeds (hardcoded, not generated). Use with
      /identity/api/v2/vehicle/vehicles (list own) and
      /identity/api/v2/vehicle/{carId}/location to test BOLA: authenticate
      as one owner and request another owner's carId."
    value:
      adam007@example.com:
        carId: f89b5f21-7829-45cb-a650-299a61090378
        vin: 7ECOX34KJTV359804
      pogba006@example.com:
        carId: cd515c12-0fc1-48ae-8b61-9230b70a845b
        vin: 8VAUI03PRUQ686911
      robot001@example.com:
        carId: 4bae9968-ec7f-4de3-a3a0-ba1b2ab5e5e5
        vin: 0NKPZ09IHOP508673
      test@example.com:
        carId: 1929186d-8b67-4163-a208-de52a41f7301
        vin: 8IGEF39BZUJ159285
      admin@example.com:
        carId: f5c506f5-3af2-4120-926c-64ad8b10ddc2
        vin: 6NBBY70FWUM324316

  - name: seeded_coupons
    description: "3 coupon codes seeded into Mongo by
      services/community/api/seed/seeder.go, redeemable via workshop's
      POST /workshop/api/shop/apply_coupon and validated via community's
      POST /community/api/v2/coupon/validate-coupon. Use to test
      reuse/replay (same code applied twice) and cross-user redemption."
    value:
      - code: TRAC075
        amount: 75
      - code: TRAC065
        amount: 65
      - code: TRAC125
        amount: 125

  - name: seeded_shop_products
    description: "2 products seeded by
      services/workshop/core/management/commands/seed_database.py
      (create_products), orderable via POST /workshop/api/shop/orders."
    value:
      - name: Seat
        price: 10
      - name: Wheel
        price: 10

  - name: seeded_orders
    description: "Up to 5 orders auto-created at workshop boot
      (create_orders in seed_database.py), one per each of the first 5 users
      by ascending identity user id (id order is boot-time dependent, not a
      fixed list of emails — enumerate via an authenticated
      GET /workshop/api/shop/orders/all as Admin to get current order IDs
      and owners for this boot). Use to test BOLA on
      GET/PUT /workshop/api/shop/orders/{order_id} across different owners."
    value: null

  - name: seeded_forum_posts
    description: "10 community forum posts seeded by
      services/community/api/seed/seeder.go on first community boot (skipped
      if the Mongo 'post' collection is already non-empty), authored
      round-robin by adam007@example.com, pogba006@example.com,
      robot001@example.com. Mongo ObjectIDs are generated at seed time, not
      fixed — enumerate via GET /community/api/v2/community/posts/recent or
      /community/api/v2/community/posts/search?title=... to get current
      postIDs for this boot. Titles are stable across reseeds: 'Best Car
      Maintenance Tips', 'My New Car Experience', 'Car Wash
      Recommendations', 'Electric vs Gas Cars', 'Road Trip Essentials', 'Car
      Insurance Advice', 'Winter Tire Discussion', 'Car Audio Upgrades',
      'Fuel Economy Tips', 'Classic Car Restoration'. Use with
      POST /community/api/v2/community/posts/{postID}/comment and
      GET /community/api/v2/community/posts/{postID} to test BOLA/IDOR
      across the 3 authors."
    value: null

  - name: seeded_mechanics
    description: "2 mechanics seeded by seed_database.py
      (create_mechanics): jhon@example.com (mechanic_code TRAC_JHN) and
      james@example.com (mechanic_code TRAC_JME). Up to 5 ServiceRequest
      rows are auto-created (create_reports) and assigned to a random one of
      these two mechanics against a random seeded vehicle — enumerate
      current assignment via an authenticated
      GET /workshop/api/mechanic/service_requests as each mechanic."
    value:
      - name: Jhon
        email: jhon@example.com
        mechanic_code: TRAC_JHN
      - name: James
        email: james@example.com
        mechanic_code: TRAC_JME
EOF

echo "[seed] Done. Wrote $NIRO_DIR/credentials.yaml and $NIRO_DIR/fixtures.yaml"
