#!/usr/bin/env bash
# seed.sh — Initialize the DVWA database and generate credentials.yaml + fixtures.yaml.
#
# Drives DVWA's own setup.php (POST create_db) with the CSRF token to create the
# database tables and seed the default users (admin/password + 4 standard users).
# Then emits niro/credentials.yaml and niro/fixtures.yaml describing the seeded
# actors and reference data. Idempotent: setup.php drops and recreates the DB.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIRO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RUN_DIR="$SCRIPT_DIR/run"
PORT="${DVWA_PORT:-4280}"
BASE_URL="http://127.0.0.1:${PORT}"
COOKIE_JAR="$RUN_DIR/seed_cookies.txt"

mkdir -p "$RUN_DIR"
rm -f "$COOKIE_JAR"

# ---------------------------------------------------------------------------
# 1. Wait for the app to respond.
# ---------------------------------------------------------------------------
for i in $(seq 1 60); do
  if curl -sf -o /dev/null "$BASE_URL/login.php" 2>/dev/null; then
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "[seed] ERROR: DVWA not reachable at $BASE_URL" >&2
    exit 1
  fi
  sleep 1
done

# ---------------------------------------------------------------------------
# 2. Drive setup.php to create/reset the database.
#    setup.php does not require authentication but does require a CSRF token.
# ---------------------------------------------------------------------------
echo "[seed] fetching CSRF token from setup.php"
SETUP_HTML="$(curl -s -c "$COOKIE_JAR" "$BASE_URL/setup.php")"
USER_TOKEN="$(printf '%s' "$SETUP_HTML" | grep -oE "name='user_token' value='[a-f0-9]+'" | head -1 | sed "s/.*value='//; s/'$//")"

if [ -z "$USER_TOKEN" ]; then
  echo "[seed] ERROR: could not extract CSRF token from setup.php" >&2
  exit 1
fi

echo "[seed] creating/resetting database via setup.php"
curl -s -b "$COOKIE_JAR" -c "$COOKIE_JAR" \
  -X POST "$BASE_URL/setup.php" \
  -d "create_db=Create+%2F+Reset+Database&user_token=${USER_TOKEN}" \
  -o /dev/null

# ---------------------------------------------------------------------------
# 3. Verify login as admin/password succeeds.
# ---------------------------------------------------------------------------
echo "[seed] verifying admin login"
LOGIN_HTML="$(curl -s -c "$COOKIE_JAR" "$BASE_URL/login.php")"
LOGIN_TOKEN="$(printf '%s' "$LOGIN_HTML" | grep -oE "name='user_token' value='[a-f0-9]+'" | head -1 | sed "s/.*value='//; s/'$//")"

if [ -z "$LOGIN_TOKEN" ]; then
  echo "[seed] ERROR: could not extract CSRF token from login.php" >&2
  exit 1
fi

LOGIN_RESULT="$(curl -s -b "$COOKIE_JAR" -c "$COOKIE_JAR" -L \
  -X POST "$BASE_URL/login.php" \
  -d "username=admin&password=password&Login=Login&user_token=${LOGIN_TOKEN}")"

if printf '%s' "$LOGIN_RESULT" | grep -q "Welcome to Damn Vulnerable Web Application"; then
  echo "[seed] admin login verified"
else
  echo "[seed] ERROR: admin login verification failed" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 4. Verify a vulnerability module is reachable.
# ---------------------------------------------------------------------------
SQLI_HTML="$(curl -s -b "$COOKIE_JAR" "$BASE_URL/vulnerabilities/sqli/")"
if printf '%s' "$SQLI_HTML" | grep -qi "SQL Injection"; then
  echo "[seed] SQL Injection module reachable"
else
  echo "[seed] WARNING: SQL Injection module not reachable" >&2
fi

# ---------------------------------------------------------------------------
# 5. Generate niro/credentials.yaml
# ---------------------------------------------------------------------------
cat > "$NIRO_DIR/credentials.yaml" <<'EOF'
# Generated by niro/harness/seed.sh — do not commit (gitignored).
# DVWA default seeded users. Security level is set to 'low' via
# DEFAULT_SECURITY_LEVEL so the full vulnerability catalog is exercisable.
credentials:
  - description: >
      DVWA admin user. Global administrator with role='admin'. Login: POST
      /login.php with form fields {username, password, Login='Login',
      user_token}. The user_token is a CSRF token rendered as a hidden input
      named 'user_token' on the login page; fetch GET /login.php, extract
      value, then POST. On success the session cookie (PHPSESSID)
      authenticates subsequent requests and a redirect to /index.php follows.
      Security level defaults to 'low' exposing the full vulnerability
      catalog. Pair with standard users for vertical-escalation tests.
    type: username_password
    identifier: admin
    secret: password

  - description: >
      Standard user 'gordonb' (Gordon Brown). Role: user (no admin privilege).
      Login: same form POST as admin. DVWA has no per-user data ownership
      model, so horizontal escalation manifests as access to the shared
      guestbook, user list, and vulnerability modules. Pair with other
      standard users for horizontal-escalation tests.
    type: username_password
    identifier: gordonb
    secret: abc123

  - description: >
      Standard user '1337' (Hack Me). Role: user. Same login flow and shared
      data model as gordonb. Pair with gordonb/pablo/smithy for
      horizontal-escalation tests across the shared vulnerability surfaces.
    type: username_password
    identifier: "1337"
    secret: charley

  - description: >
      Standard user 'pablo' (Pablo Picasso). Role: user. Same login flow and
      shared data model. Pair with other standard users.
    type: username_password
    identifier: pablo
    secret: letmein

  - description: >
      Standard user 'smithy' (Bob Smith). Role: user. Same login flow and
      shared data model. Pair with other standard users.
    type: username_password
    identifier: smithy
    secret: password
EOF
echo "[seed] wrote $NIRO_DIR/credentials.yaml"

# ---------------------------------------------------------------------------
# 6. Generate niro/fixtures.yaml
# ---------------------------------------------------------------------------
cat > "$NIRO_DIR/fixtures.yaml" <<EOF
# Generated by niro/harness/seed.sh — do not commit (gitignored).
# Reference points into DVWA's seeded state (created by setup.php).
fixtures:
  - name: target_url
    description: "Base URL of the running DVWA instance. All vulnerability
      modules and API routes are under this root."
    value: "$BASE_URL"

  - name: security_level
    description: "DVWA security level set via DEFAULT_SECURITY_LEVEL env var.
      'low' exposes the full vulnerability catalog with minimal input
      sanitization. Can be changed per-session via the 'security' cookie
      (values: low, medium, high, impossible)."
    value: low

  - name: seeded_users
    description: "Users created by setup.php. All have MD5-hashed passwords.
      admin has role='admin'; the rest have role='user'. User IDs are 1-5."
    value:
      - user_id: 1
        username: admin
        password: password
        role: admin
      - user_id: 2
        username: gordonb
        password: abc123
        role: user
      - user_id: 3
        username: "1337"
        password: charley
        role: user
      - user_id: 4
        username: pablo
        password: letmein
        role: user
      - user_id: 5
        username: smithy
        password: password
        role: user

  - name: guestbook_entry
    description: "Seeded guestbook comment used by the Stored XSS and SQLi
      modules. The guestbook table has one row: comment_id=1,
      comment='This is a test comment.', name='test'."
    value:
      comment_id: 1
      comment: "This is a test comment."
      name: test

  - name: vulnerability_modules
    description: "DVWA vulnerability modules reachable after login. Each is at
      /vulnerabilities/<name>/. These are the exercisable attack surfaces at
      security level 'low'."
    value:
      - sqli
      - sqli_blind
      - xss_r
      - xss_s
      - xss_d
      - brute
      - csrf
      - exec
      - fi
      - upload
      - captcha
      - csp
      - javascript
      - open_redirect
      - weak_id
      - authbypass
      - bac
      - cryptography
      - api

  - name: db_config
    description: "Database connection details from config.inc.php (env-driven).
      MariaDB 10 running in the 'db' service; DVWA connects as the dvwa user."
    value:
      db_server: db
      db_database: dvwa
      db_user: dvwa
      db_port: 3306
EOF
echo "[seed] wrote $NIRO_DIR/fixtures.yaml"

echo "[seed] done"
