#!/usr/bin/env bash
set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$(cd "$HARNESS_DIR/.." && pwd)"
COOKIE_JAR="$HARNESS_DIR/run/setup.cookies"
SETUP_HTML="$HARNESS_DIR/run/setup.html"
mkdir -p "$HARNESS_DIR/run"

curl --fail --silent --show-error --cookie-jar "$COOKIE_JAR" \
  http://127.0.0.1:4280/setup.php > "$SETUP_HTML"
TOKEN="$(sed -n "s/.*name='user_token' value='\([^']*\)'.*/\1/p" "$SETUP_HTML" | head -n 1)"
test -n "$TOKEN"
curl --fail --silent --show-error --location --cookie "$COOKIE_JAR" \
  --data-urlencode "create_db=Create / Reset Database" \
  --data-urlencode "user_token=$TOKEN" \
  http://127.0.0.1:4280/setup.php >/dev/null

API_TOKEN_RESPONSE="$(curl --fail --silent --show-error \
  --user '1471.dvwa.digi.ninja:ABigLongSecret' \
  --data-urlencode 'grant_type=password' \
  --data-urlencode 'username=mrbennett' \
  --data-urlencode 'password=becareful' \
  http://127.0.0.1:4280/vulnerabilities/api/v2/login/login)"
API_ACCESS_TOKEN="$(jq --exit-status --raw-output '.access_token' <<<"$API_TOKEN_RESPONSE")"
test -n "$API_ACCESS_TOKEN"

cat > "$CONFIG_DIR/credentials.yaml" <<'EOF'
credentials:
  - credential_id: GLOBAL_ADMIN
    description: "DVWA global administrator. Login with POST /login.php form fields username, password, Login, and the page's user_token CSRF value. Has role=admin and may access every authenticated lab. Default security level is low for this test runtime."
    type: username_password
    identifier: admin
    secret: password
  - credential_id: STANDARD_USER_A
    description: "DVWA standard user Gordon Brown (user_id 2, role=user). Login with POST /login.php form fields username, password, Login, and user_token. Pair with STANDARD_USER_B for horizontal access tests; this account does not have admin privileges."
    type: username_password
    identifier: gordonb
    secret: abc123
  - credential_id: STANDARD_USER_B
    description: "DVWA standard user Pablo Picasso (user_id 4, role=user). Login with POST /login.php form fields username, password, Login, and user_token. Pair with STANDARD_USER_A for horizontal access tests; this account does not have admin privileges."
    type: username_password
    identifier: pablo
    secret: letmein
EOF

cat >> "$CONFIG_DIR/credentials.yaml" <<EOF
  - credential_id: API_ORDER_BEARER
    description: "Fresh short-lived bearer credential for authenticated reads and writes under /vulnerabilities/api/v1/order and /vulnerabilities/api/v2/order. Send as Authorization: Bearer <token>. Regenerated by seed/reset; access token lifetime is 180 seconds."
    type: bearer_token
    secret: "Bearer $API_ACCESS_TOKEN"
EOF

cat > "$CONFIG_DIR/fixtures.yaml" <<'EOF'
fixtures:
  - name: standard_user_a
    description: "Database identity owned by STANDARD_USER_A for broken-access-control and user-ID tests."
    value:
      user_id: 2
      username: gordonb
  - name: standard_user_b
    description: "Distinct database identity owned by STANDARD_USER_B for cross-user access tests."
    value:
      user_id: 4
      username: pablo
  - name: additional_users
    description: "Other deterministic DVWA user records available as object-level access targets."
    value:
      - {user_id: 3, username: "1337"}
      - {user_id: 5, username: smithy}
  - name: guestbook_comment
    description: "Deterministic guestbook row created by DVWA's setup bootstrap."
    value:
      comment_id: 1
      name: test
  - name: destructive_setup_reset
    description: "Explicit authorization for this isolated checkout-local target: POST /setup.php with create_db and its user_token may destructively recreate the DVWA database. Run niro/harness/reset.sh afterward to restore the deterministic DB, credentials, and fixtures baseline."
    value:
      endpoint: /setup.php
      method: POST
      form_field: create_db
      authorized: true
      restoration_command: niro/harness/reset.sh
  - name: api_orders
    description: "Deterministic in-memory orders available through both authenticated v1 and v2 order APIs; use API_ORDER_BEARER. Writes are request-local, so the seed baseline remains deterministic."
    value:
      collection_paths:
        - /vulnerabilities/api/v1/order/
        - /vulnerabilities/api/v2/order/
      order_ids: [1, 2, 3]
      writable_methods: [POST, PUT, DELETE]
EOF

curl --fail --silent --show-error http://127.0.0.1:4280/login.php >/dev/null
docker compose -p niro-dvwa -f "$HARNESS_DIR/compose.yml" exec -T db \
  mariadb -udvwa '-pp@ssw0rd' -e 'SELECT COUNT(*) FROM dvwa.users HAVING COUNT(*) = 5' >/dev/null
