#!/usr/bin/env bash
# Shared paths, ports, and helpers for the Niro-managed Dify harness.
# Sourced by start.sh / stop.sh / seed.sh / reset.sh — not meant to be run directly.

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIRO_DIR="$(cd "$HARNESS_DIR/.." && pwd)"
REPO_ROOT="$(cd "$NIRO_DIR/.." && pwd)"
RUN_DIR="$HARNESS_DIR/run"
ENV_FILE="$RUN_DIR/.env"
COMPOSE_FILE="$HARNESS_DIR/compose.yaml"
PROJECT_NAME="niro-dify"

WEB_PORT="${NIRO_WEB_PORT:-3000}"
API_PORT="${NIRO_API_PORT:-5001}"

compose() {
  docker compose \
    --project-name "$PROJECT_NAME" \
    -f "$COMPOSE_FILE" \
    --env-file "$ENV_FILE" \
    "$@"
}

# Wait until a URL responds without a connection error (any HTTP status,
# since a redirect/401/404 still proves the service is up and answering).
wait_for_http() {
  local url="$1"
  local timeout="${2:-300}"
  local start
  start=$(date +%s)
  until curl -fsS -o /dev/null "$url" 2>/dev/null || curl -sS -o /dev/null --max-time 3 "$url" 2>/dev/null; do
    if [ $(( $(date +%s) - start )) -ge "$timeout" ]; then
      echo "Timed out waiting for $url to answer" >&2
      return 1
    fi
    sleep 3
  done
}

# Ensure run/ exists and a stable .env with generated secrets is present.
# Idempotent: re-running start.sh never rotates existing secrets, so
# containers restart against the same baseline.
ensure_env_file() {
  mkdir -p "$RUN_DIR/volumes/db" "$RUN_DIR/volumes/pgvector" "$RUN_DIR/volumes/redis" \
    "$RUN_DIR/volumes/storage" "$RUN_DIR/volumes/plugin_daemon"
  # The api/worker containers run as uid 1001 (see api/Dockerfile); the bind
  # mount is host-owned, so open it up for the container's non-root user.
  chmod -R 0777 "$RUN_DIR/volumes/storage" "$RUN_DIR/volumes/plugin_daemon" 2>/dev/null || true

  if [ ! -f "$ENV_FILE" ]; then
    echo "harness: generating $ENV_FILE (fresh local secrets)"
    local secret_key db_password redis_password pgvector_password plugin_daemon_key plugin_inner_api_key
    secret_key=$(openssl rand -base64 42 | tr -d '\n')
    db_password=$(openssl rand -hex 16)
    redis_password=$(openssl rand -hex 16)
    pgvector_password=$(openssl rand -hex 16)
    plugin_daemon_key=$(openssl rand -hex 24)
    plugin_inner_api_key=$(openssl rand -hex 24)
    cat > "$ENV_FILE" <<EOF
# Generated by niro/harness/lib.sh. Local-only secrets for the Niro test
# harness — never used outside this checkout-local runtime. Not committed
# (niro/harness/run/ is gitignored).
REPO_ROOT=$REPO_ROOT
HARNESS_DIR=$HARNESS_DIR
RUN_DIR=$RUN_DIR
WEB_PORT=$WEB_PORT
API_PORT=$API_PORT
SECRET_KEY=$secret_key
DB_PASSWORD=$db_password
REDIS_PASSWORD=$redis_password
PGVECTOR_PASSWORD=$pgvector_password
PLUGIN_DAEMON_KEY=$plugin_daemon_key
PLUGIN_INNER_API_KEY=$plugin_inner_api_key
EOF
  fi
}
