#!/usr/bin/env python3
"""Turn seed_accounts.py's JSON output into niro/credentials.yaml and
niro/fixtures.yaml. Runs on the HOST (not in a container) with only the
standard library, so it has no dependency on the api image's virtualenv.

Usage: seed.sh pipes the extracted JSON blob to this script's stdin,
       with the niro/ config directory as argv[1].
"""

from __future__ import annotations

import json
import sys


def yaml_str(value: str) -> str:
    """Render a Python string as a double-quoted YAML scalar."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def folded_description(text: str) -> str:
    """Render a long description as a YAML folded-looking block using a
    quoted scalar with explicit line continuation, matching the style of
    credentials.yaml.example (one logical string, wrapped for readability)."""
    return yaml_str(" ".join(text.split()))


def main() -> None:
    niro_dir = sys.argv[1]
    payload = json.load(sys.stdin)
    orgs = {o["org"]: o for o in payload["orgs"]}
    org_a, org_b = orgs["A"], orgs["B"]

    login_note = (
        "Login: POST /console/api/login with JSON body "
        '{"email": "<identifier>", "password": "<base64(plaintext password)>", "remember_me": false}. '
        "IMPORTANT: the password field is base64-encoded plaintext, not a real cipher "
        "(controllers/console/wraps.py:decrypt_password_field only base64-decodes it) -- "
        "base64-encode the secret below before sending it."
    )

    credentials = f"""\
# yaml-language-server: $schema=https://niro.apxlabs.ai/schema/v1/credentials.json
#
# Generated by niro/harness/seed.sh from niro/harness/seed_accounts.py.
# Do not hand-edit -- re-run seed.sh (or reset.sh) to regenerate. Gitignored.
#
# Two isolated workspaces ("orgs"), each with an owner (privileged: can
# manage members, delete the workspace, invite/remove users) and a normal
# member (no admin surface). Org A and Org B own DIFFERENT apps/datasets
# (see ../fixtures.yaml) so cross-org access attempts have something
# concrete to fail at.
#
# Escalation coverage:
#   - Vertical:   MEMBER_ORG_A vs OWNER_ORG_A (same tenant, different role)
#                 and MEMBER_ORG_B vs OWNER_ORG_B.
#   - Horizontal: OWNER_ORG_A vs OWNER_ORG_B, and MEMBER_ORG_A vs
#                 MEMBER_ORG_B (same role, different tenant/resources).
#
# ALLOW_REGISTER and ALLOW_CREATE_WORKSPACE are enabled in this harness
# (both default off upstream) so self-registration and workspace-creation
# endpoints are live, reachable surfaces too -- not just these 4 seeded
# accounts.

credentials:
  - credential_id: OWNER_ORG_A
    description: {folded_description(
        f"Owner of tenant '{org_a['tenant_name']}' (tenant_id {org_a['tenant_id']}). "
        f"Owns app '{org_a['app_name']}' (id {org_a['app_id']}) and dataset "
        f"'{org_a['dataset_name']}' (id {org_a['dataset_id']}). Owner-only surfaces: "
        "workspace member invite/remove/role-change, workspace deletion, workspace "
        "API-key management. " + login_note + " Pair with MEMBER_ORG_A to verify a "
        "normal member is rejected at owner-only endpoints (expect 403). Pair with "
        "OWNER_ORG_B to verify tenant isolation across two org-scoped owners."
    )}
    type: username_password
    identifier: {org_a['owner_email']}
    secret: {yaml_str(org_a['owner_password'])}

  - credential_id: MEMBER_ORG_A
    description: {folded_description(
        f"Normal-role member of tenant '{org_a['tenant_name']}' (tenant_id "
        f"{org_a['tenant_id']}). Created app '{org_a['app_name']}' (id "
        f"{org_a['app_id']}) and dataset '{org_a['dataset_name']}' (id "
        f"{org_a['dataset_id']}) within the workspace -- Dify apps/datasets are "
        "workspace-shared resources (any member of the tenant can see them), so use "
        "this account's tenant scope, not per-resource private ownership, for "
        "isolation tests. No admin flags beyond the 'normal' role. " + login_note +
        " Pair with OWNER_ORG_A for vertical-escalation tests (expect 403 on "
        "owner-only endpoints). Pair with MEMBER_ORG_B for horizontal-escalation "
        "tests across tenants (expect 403/404 reading Org B's app or dataset by id)."
    )}
    type: username_password
    identifier: {org_a['member_email']}
    secret: {yaml_str(org_a['member_password'])}

  - credential_id: OWNER_ORG_B
    description: {folded_description(
        f"Owner of tenant '{org_b['tenant_name']}' (tenant_id {org_b['tenant_id']}). "
        f"Owns app '{org_b['app_name']}' (id {org_b['app_id']}) and dataset "
        f"'{org_b['dataset_name']}' (id {org_b['dataset_id']}). Same owner-only "
        "surfaces as OWNER_ORG_A, scoped to this separate tenant. " + login_note +
        " Pair with OWNER_ORG_A for horizontal-escalation / tenant-isolation tests "
        "between two org-scoped owners. Pair with MEMBER_ORG_B for vertical-"
        "escalation tests within Org B."
    )}
    type: username_password
    identifier: {org_b['owner_email']}
    secret: {yaml_str(org_b['owner_password'])}

  - credential_id: MEMBER_ORG_B
    description: {folded_description(
        f"Normal-role member of tenant '{org_b['tenant_name']}' (tenant_id "
        f"{org_b['tenant_id']}). Created app '{org_b['app_name']}' (id "
        f"{org_b['app_id']}) and dataset '{org_b['dataset_name']}' (id "
        f"{org_b['dataset_id']}) within the workspace. Same notes as MEMBER_ORG_A "
        "about shared workspace resource visibility. " + login_note +
        " Pair with OWNER_ORG_B for vertical-escalation tests. Pair with "
        "MEMBER_ORG_A for horizontal-escalation tests across tenants."
    )}
    type: username_password
    identifier: {org_b['member_email']}
    secret: {yaml_str(org_b['member_password'])}
"""

    fixtures = f"""\
# yaml-language-server: $schema=https://niro.apxlabs.ai/schema/v1/fixtures.json
#
# Generated by niro/harness/seed.sh from niro/harness/seed_accounts.py.
# Do not hand-edit -- re-run seed.sh (or reset.sh) to regenerate. Gitignored.

fixtures:
  - name: org_a
    description: {folded_description(
        "Niro Org A workspace: tenant id plus the fixture app and dataset seeded "
        "inside it (both created by MEMBER_ORG_A, workspace-visible to OWNER_ORG_A "
        "too). Use these ids to build cross-tenant IDOR attempts from Org B's "
        "credentials (expect denial)."
    )}
    value:
      tenant_id: {org_a['tenant_id']}
      tenant_name: {yaml_str(org_a['tenant_name'])}
      app_id: {org_a['app_id']}
      app_name: {yaml_str(org_a['app_name'])}
      dataset_id: {org_a['dataset_id']}
      dataset_name: {yaml_str(org_a['dataset_name'])}

  - name: org_b
    description: {folded_description(
        "Niro Org B workspace: tenant id plus the fixture app and dataset seeded "
        "inside it (both created by MEMBER_ORG_B, workspace-visible to OWNER_ORG_B "
        "too). Use these ids to build cross-tenant IDOR attempts from Org A's "
        "credentials (expect denial)."
    )}
    value:
      tenant_id: {org_b['tenant_id']}
      tenant_name: {yaml_str(org_b['tenant_name'])}
      app_id: {org_b['app_id']}
      app_name: {yaml_str(org_b['app_name'])}
      dataset_id: {org_b['dataset_id']}
      dataset_name: {yaml_str(org_b['dataset_name'])}

  - name: console_login
    description: {folded_description(
        "Console session login. POST /console/api/login, JSON body "
        "{email, password, remember_me}. password is base64(plaintext) -- see "
        "each credential's description in ../credentials.yaml for the exact "
        "caveat and citation."
    )}
    value:
      method: POST
      path: /console/api/login

  - name: self_service_flows_enabled
    description: {folded_description(
        "ALLOW_REGISTER and ALLOW_CREATE_WORKSPACE are both true in this harness "
        "(default false upstream), so /console/api/email-register/* and "
        "workspace-creation endpoints are live, reachable, unauthenticated-or-low-"
        "privilege surfaces here, not just the 4 seeded accounts above."
    )}
    value: true
"""

    with open(f"{niro_dir}/credentials.yaml", "w") as f:
        f.write(credentials)
    with open(f"{niro_dir}/fixtures.yaml", "w") as f:
        f.write(fixtures)


if __name__ == "__main__":
    main()
