#!/usr/bin/env python3
"""Render niro/credentials.yaml and niro/fixtures.yaml from seed_dify.py's
JSON output.

Usage: seed_dify.py's stdout JSON is piped in on stdin:
    docker compose exec -T api python3 /tmp/niro_seed.py | \
        python3 niro/harness/render_niro_files.py <niro_config_dir>

Kept separate from seed_dify.py because seed_dify.py runs inside the api
container (only stdlib + app deps available there); this renderer runs on
the host, where PyYAML is available, and owns the actual niro/*.yaml file
format/schema decisions.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml


HEADER = (
    "# yaml-language-server: $schema=https://niro.apxlabs.ai/schema/v1/{schema}.json\n"
    "#\n"
    "# GENERATED by niro/harness/seed.sh -> render_niro_files.py. Do not edit by\n"
    "# hand; re-run niro/harness/seed.sh (or reset.sh) to regenerate.\n"
    "# Source of truth for how this is produced: niro/harness/seed_dify.py.\n"
)


def dump(obj: dict) -> str:
    return yaml.safe_dump(obj, sort_keys=False, allow_unicode=True, width=100)


def build_credentials(data: dict) -> dict:
    acc = data["accounts"]
    apps = data["apps"]
    datasets = data["datasets"]
    pw = data["seed_password"]

    login_note = (
        "Login: POST /console/api/login with body {{email, password, language}}. "
        "IMPORTANT: password must be base64-encoded before sending (the console "
        "wraps.py `decrypt_password_field` decorator base64-decodes it server-side; "
        "see web/utils/encryption.ts `encryptField` for the exact client behavior). "
        "Plain-text password is: {password!r}."
    )

    def account_desc(role_label: str, tenant_label: str, ownership: str, pairing: str) -> str:
        return (
            f"{role_label} in {tenant_label}. {ownership} {login_note.format(password=pw)} {pairing}"
        )

    credentials = [
        {
            "credential_id": "OWNER_A",
            "description": account_desc(
                "Role: owner (full tenant control: billing, members, delete workspace)",
                "Tenant 'Niro Org A' (id "
                + data["tenants"]["org_a"]["id"]
                + ")",
                "Owns 'Niro Chatbot A' app and 'Niro Dataset A' dataset (see fixtures app_a / dataset_a).",
                "Pair with OWNER_B for horizontal cross-tenant isolation tests (Org A must never reach "
                "Org B's app/dataset/members and vice versa). Pair with ADMIN_A/EDITOR_A/NORMAL_A/DSOP_A "
                "for vertical-escalation tests: those lower roles must be denied owner-only actions "
                "(delete workspace, manage billing, transfer ownership, remove the owner).",
            ),
            "type": "username_password",
            "identifier": acc["owner_a"]["email"],
            "secret": pw,
        },
        {
            "credential_id": "ADMIN_A",
            "description": account_desc(
                "Role: admin (member/app management, cannot delete workspace or change owner)",
                "Tenant 'Niro Org A' (same tenant as OWNER_A/EDITOR_A/NORMAL_A/DSOP_A)",
                "Does not own any app/dataset itself; acts on Org A's shared resources.",
                "Pair with OWNER_A to verify admin is denied owner-only actions. Pair with EDITOR_A/"
                "NORMAL_A/DSOP_A to verify admin can manage members while those lower roles cannot.",
            ),
            "type": "username_password",
            "identifier": acc["admin_a"]["email"],
            "secret": pw,
        },
        {
            "credential_id": "EDITOR_A",
            "description": account_desc(
                "Role: editor (can build/edit apps and datasets, cannot manage members or billing)",
                "Tenant 'Niro Org A'",
                "Does not own any app/dataset itself.",
                "Pair with ADMIN_A/OWNER_A to verify editor is denied member-management and billing "
                "endpoints. Pair with NORMAL_A to verify normal cannot edit apps that editor can.",
            ),
            "type": "username_password",
            "identifier": acc["editor_a"]["email"],
            "secret": pw,
        },
        {
            "credential_id": "NORMAL_A",
            "description": account_desc(
                "Role: normal (lowest general member role: use published apps, cannot edit them)",
                "Tenant 'Niro Org A'",
                "Does not own any app/dataset itself.",
                "Pair with EDITOR_A/ADMIN_A/OWNER_A for vertical-escalation tests (normal must be denied "
                "app-editing, member-management, and dataset-management endpoints).",
            ),
            "type": "username_password",
            "identifier": acc["normal_a"]["email"],
            "secret": pw,
        },
        {
            "credential_id": "DSOP_A",
            "description": account_desc(
                "Role: dataset_operator (dataset-management scope only; no app-editing or member rights)",
                "Tenant 'Niro Org A'",
                "Does not own any app/dataset itself, but the role is scoped to dataset endpoints.",
                "Pair with NORMAL_A/OWNER_A to verify dataset_operator can manage 'Niro Dataset A' "
                "(dataset_a fixture) while being denied app-editing and member-management endpoints "
                "that even NORMAL_A's peers should not reach either.",
            ),
            "type": "username_password",
            "identifier": acc["dsop_a"]["email"],
            "secret": pw,
        },
        {
            "credential_id": "OWNER_B",
            "description": account_desc(
                "Role: owner, full control of its own tenant",
                "Tenant 'Niro Org B' (id "
                + data["tenants"]["org_b"]["id"]
                + ") -- separate tenant from Org A, no shared membership",
                "Owns 'Niro Chatbot B' app (see fixtures app_b).",
                "Pair with OWNER_A/NORMAL_A for horizontal cross-tenant isolation tests: authenticate as "
                "Owner B and attempt to read/modify Org A's app, dataset, or member list (app_a, "
                "dataset_a fixtures) -- expect 403/404. Symmetric checks (Org A reaching Org B's "
                "app_b) also apply.",
            ),
            "type": "username_password",
            "identifier": acc["owner_b"]["email"],
            "secret": pw,
        },
        {
            "credential_id": "NORMAL_B",
            "description": account_desc(
                "Role: normal member",
                "Tenant 'Niro Org B'",
                "Does not own any app/dataset itself.",
                "Pair with NORMAL_A for horizontal isolation tests between two same-role users in "
                "different tenants (neither should reach the other's tenant resources).",
            ),
            "type": "username_password",
            "identifier": acc["normal_b"]["email"],
            "secret": pw,
        },
        {
            "credential_id": "APP_A_SERVICE_API_KEY",
            "description": (
                "Service API key for app_a ('Niro Chatbot A', tenant Niro Org A). Send as "
                "`Authorization: Bearer <token>` against /v1/* service API endpoints "
                "(api/controllers/service_api/wraps.py). Use to test whether this app-scoped key can "
                "reach app_b's data or other tenants' service API surface -- it must not."
            ),
            "type": "bearer_token",
            "secret": f"Bearer {apps['app_a']['api_key']}",
        },
        {
            "credential_id": "APP_B_SERVICE_API_KEY",
            "description": (
                "Service API key for app_b ('Niro Chatbot B', tenant Niro Org B). Same auth shape as "
                "APP_A_SERVICE_API_KEY. Use as the cross-tenant counterpart when testing service-API "
                "key isolation."
            ),
            "type": "bearer_token",
            "secret": f"Bearer {apps['app_b']['api_key']}",
        },
        {
            "credential_id": "DATASET_A_API_KEY",
            "description": (
                "Dataset API key, tenant Niro Org A. Send as `Authorization: Bearer <token>` against "
                "/v1/datasets/* endpoints. IMPORTANT -- this key's real effective privilege is TENANT-"
                "scoped, not dataset-scoped, despite the console UI presenting it as belonging to a "
                "single dataset (dataset_a, 'Niro Dataset A'): controllers/service_api/wraps.py "
                "authenticates a DATASET-type key by (type, tenant_id) alone, then looks the requested "
                "dataset up by (dataset_id from the URL, tenant_id) -- it never compares against a "
                "per-key dataset id, and the ApiToken model has no mapped dataset_id column to compare "
                "against even if it tried. So this key legitimately reaches every dataset created in "
                "Org A, now or later -- that is intended-by-current-code-path behavior, not an escalation, "
                "even though it may be worth flagging as a UI/access-model mismatch. It must still be "
                "denied Org B's resources entirely (Org B has no dataset seeded)."
            ),
            "type": "bearer_token",
            "secret": f"Bearer {datasets['dataset_a']['api_key']}",
        },
    ]

    return {"credentials": credentials}


def _without_secret(value: dict) -> dict:
    """Fixtures announce reference points, not auth material -- api_key lives
    in credentials.yaml (APP_A_SERVICE_API_KEY / APP_B_SERVICE_API_KEY /
    DATASET_A_API_KEY) only."""
    return {k: v for k, v in value.items() if k != "api_key"}


def build_fixtures(data: dict) -> dict:
    fixtures = [
        {
            "name": "tenant_org_a",
            "description": "Seeded tenant 'Niro Org A'. Owns app_a and dataset_a. Members: OWNER_A, "
            "ADMIN_A, EDITOR_A, NORMAL_A, DSOP_A credentials.",
            "value": data["tenants"]["org_a"],
        },
        {
            "name": "tenant_org_b",
            "description": "Seeded tenant 'Niro Org B', fully independent from Org A (no shared "
            "members). Owns app_b. Members: OWNER_B, NORMAL_B credentials.",
            "value": data["tenants"]["org_b"],
        },
        {
            "name": "app_a",
            "description": "Seeded chat app owned by Org A. id/mode useful for /console/api/apps/<id>/* "
            "and /v1/* (with APP_A_SERVICE_API_KEY) endpoint construction. api_key lives in "
            "credentials.yaml, not here.",
            "value": _without_secret(data["apps"]["app_a"]),
        },
        {
            "name": "app_b",
            "description": "Seeded chat app owned by Org B, the cross-tenant counterpart to app_a. "
            "api_key lives in credentials.yaml, not here.",
            "value": _without_secret(data["apps"]["app_b"]),
        },
        {
            "name": "dataset_a",
            "description": "Seeded empty dataset owned by Org A. Org B intentionally has no dataset. "
            "See DATASET_A_API_KEY in credentials.yaml for why this key is NOT scoped to only this "
            "dataset. api_key lives in credentials.yaml, not here.",
            "value": _without_secret(data["datasets"]["dataset_a"]),
        },
    ]
    return {"fixtures": fixtures}


def main() -> None:
    if len(sys.argv) != 2:
        print("usage: render_niro_files.py <niro_config_dir>", file=sys.stderr)
        raise SystemExit(2)
    niro_dir = Path(sys.argv[1])

    raw = sys.stdin.read()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        print("render_niro_files.py: seed script did not print valid JSON on stdout", file=sys.stderr)
        print(raw, file=sys.stderr)
        raise SystemExit(1) from exc

    creds_path = niro_dir / "credentials.yaml"
    fixtures_path = niro_dir / "fixtures.yaml"

    creds_path.write_text(HEADER.format(schema="credentials") + "\n" + dump(build_credentials(data)))
    fixtures_path.write_text(HEADER.format(schema="fixtures") + "\n" + dump(build_fixtures(data)))

    print(f"wrote {creds_path}")
    print(f"wrote {fixtures_path}")


if __name__ == "__main__":
    main()
