"""Render niro/credentials.yaml and niro/fixtures.yaml from the accounts
seed.sh just created plus the per-org app/dataset/api-key state it wrote to
niro/harness/run/state/org_{A,B}.json.

Both output files are generated, gitignored, and safe to overwrite on every
seed run -- see niro/credentials.yaml.example and niro/fixtures.yaml.example
for the format this mirrors.
"""

import argparse
import json
import os
from pathlib import Path

import yaml

CREDENTIALS_HEADER = (
    "# yaml-language-server: $schema=https://niro.apxlabs.ai/schema/v1/credentials.json\n"
    "#\n"
    "# GENERATED by niro/harness/seed.sh (niro/harness/seed/render_manifests.py).\n"
    "# Do not edit by hand -- re-run niro/harness/seed.sh instead.\n"
    "# See niro/credentials.yaml.example for the full format reference.\n\n"
)

FIXTURES_HEADER = (
    "# yaml-language-server: $schema=https://niro.apxlabs.ai/schema/v1/fixtures.json\n"
    "#\n"
    "# GENERATED by niro/harness/seed.sh (niro/harness/seed/render_manifests.py).\n"
    "# Do not edit by hand -- re-run niro/harness/seed.sh instead.\n"
    "# See niro/fixtures.yaml.example for the full format reference.\n\n"
)

LOGIN_AUTH_NOTE = (
    "Login: POST /console/api/login {email, password, remember_me}; password must be "
    "base64-ENCODED plaintext (wraps.py decrypt_password_field -- obfuscation, not real crypto; "
    "non-base64 = auth failure). Cookie auth (access_token/refresh_token/csrf_token; "
    "access_token also usable as 'Authorization: Bearer'). EVERY request, GET included, to a "
    "login-required /console/api/* route also needs header X-CSRF-Token = csrf_token cookie "
    "value, or it's rejected."
)


def build_credentials() -> dict:
    owner_a_email = os.environ["NIRO_OWNER_A_EMAIL"]
    owner_b_email = os.environ["NIRO_OWNER_B_EMAIL"]
    normal_a_email = os.environ["NIRO_NORMAL_A_EMAIL"]
    normal_b_email = os.environ["NIRO_NORMAL_B_EMAIL"]

    credentials = [
        {
            "credential_id": "OWNER_A",
            "description": (
                f"Owner of tenant 'Org A' (role: owner, Dify's highest tenant role -- full rights "
                f"over Org A's members/apps/datasets/API keys). Owns app+dataset in fixtures "
                f"org_a_app/org_a_dataset. Pair with OWNER_B for cross-tenant (horizontal) tests: "
                f"as Owner A, try to read/modify Org B's app/dataset/members, expect 403/404. "
                f"Pair with NORMAL_A for vertical-escalation tests (owner-only actions like member "
                f"management must reject NORMAL_A). {LOGIN_AUTH_NOTE}"
            ),
            "type": "username_password",
            "identifier": owner_a_email,
            "secret": os.environ["NIRO_OWNER_A_PASSWORD"],
        },
        {
            "credential_id": "NORMAL_A",
            "description": (
                f"Standard ('normal') member of tenant 'Org A', added by Owner A. Lowest role "
                f"above dataset_operator; no admin/owner capabilities, no cross-cutting flags, "
                f"owns no resources itself. Use to check Org A's app/dataset (fixtures "
                f"org_a_app/org_a_dataset) per normal-member permissions, and that owner-only "
                f"endpoints (member invite/remove, workspace transfer, API-key mgmt) reject it "
                f"with 403. {LOGIN_AUTH_NOTE}"
            ),
            "type": "username_password",
            "identifier": normal_a_email,
            "secret": os.environ["NIRO_NORMAL_A_PASSWORD"],
        },
        {
            "credential_id": "OWNER_B",
            "description": (
                f"Owner of tenant 'Org B' (role: owner), separate from Org A with no shared "
                f"membership. Owns app+dataset in fixtures org_b_app/org_b_dataset. Pair with "
                f"OWNER_A for cross-tenant isolation tests in the other direction. {LOGIN_AUTH_NOTE}"
            ),
            "type": "username_password",
            "identifier": owner_b_email,
            "secret": os.environ["NIRO_OWNER_B_PASSWORD"],
        },
        {
            "credential_id": "NORMAL_B",
            "description": (
                f"Standard ('normal') member of tenant/workspace 'Org B', invited by Owner B. "
                f"Same role and shape as NORMAL_A but in the other tenant -- pair the two for "
                f"same-role/different-tenant comparisons. {LOGIN_AUTH_NOTE}"
            ),
            "type": "username_password",
            "identifier": normal_b_email,
            "secret": os.environ["NIRO_NORMAL_B_PASSWORD"],
        },
    ]

    return {"credentials": credentials}


def build_fixtures(state_dir: Path, base_url: str) -> dict:
    org_a = json.loads((state_dir / "org_A.json").read_text())
    org_b = json.loads((state_dir / "org_B.json").read_text())

    fixtures = [
        {
            "name": "base_url",
            "description": "Base URL of this Niro-managed local Dify deployment (nginx, fronting web + console/service APIs on one origin).",
            "value": base_url,
        },
        {
            "name": "org_a_app",
            "description": (
                "Sample chatbot app ('Niro Sample Chatbot A', mode=chat) owned by Org A / "
                "OWNER_A. app_api_token is a Service API key (Authorization: Bearer <token>) "
                "scoped to this app's /v1 endpoints; use it to test whether the Service API "
                "key for Org A's app can reach Org B's app or vice versa."
            ),
            "value": {
                "tenant": "Org A",
                "app_id": org_a["app_id"],
                "app_api_token": org_a["app_api_token"],
            },
        },
        {
            "name": "org_a_dataset",
            "description": (
                "Sample empty knowledge base ('Niro Sample KB A') owned by Org A / OWNER_A. "
                "dataset_api_token is a Service API key scoped to this dataset's /v1 endpoints, "
                "or null if key generation failed (see accepted-coverage-gaps.yaml: dataset "
                "API-key generation 500s in this checkout). No documents are indexed (no "
                "embedding-model provider is configured in this harness -- also see "
                "accepted-coverage-gaps.yaml)."
            ),
            "value": {
                "tenant": "Org A",
                "dataset_id": org_a["dataset_id"],
                "dataset_api_token": org_a["dataset_api_token"],
            },
        },
        {
            "name": "org_b_app",
            "description": "Same shape as org_a_app, owned by Org B / OWNER_B. Use as the cross-tenant counterpart when testing org_a_app's isolation, and vice versa.",
            "value": {
                "tenant": "Org B",
                "app_id": org_b["app_id"],
                "app_api_token": org_b["app_api_token"],
            },
        },
        {
            "name": "org_b_dataset",
            "description": "Same shape as org_a_dataset, owned by Org B / OWNER_B.",
            "value": {
                "tenant": "Org B",
                "dataset_id": org_b["dataset_id"],
                "dataset_api_token": org_b["dataset_api_token"],
            },
        },
    ]

    return {"fixtures": fixtures}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--state-dir", required=True)
    parser.add_argument("--out-credentials", required=True)
    parser.add_argument("--out-fixtures", required=True)
    args = parser.parse_args()

    state_dir = Path(args.state_dir)

    credentials_path = Path(args.out_credentials)
    credentials_path.write_text(
        CREDENTIALS_HEADER + yaml.safe_dump(build_credentials(), sort_keys=False, width=100, allow_unicode=True)
    )

    fixtures_path = Path(args.out_fixtures)
    fixtures_path.write_text(
        FIXTURES_HEADER + yaml.safe_dump(build_fixtures(state_dir, args.base_url), sort_keys=False, width=100, allow_unicode=True)
    )


if __name__ == "__main__":
    main()
